create table Person(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
full_name varchar(100) NOT NULL UNIQUE,
year_of_birth int check ( year_of_birth > 1920 ));

insert into Person(full_name, year_of_birth)
values ('Гайдук Владимир Евгеньевич', 1991);
insert into Person(full_name, year_of_birth)
values ('Ржеуцкая Валерия Андреевна', 1994);
insert into Person(full_name, year_of_birth)
values ('Сидоров Артем Иванович', 1978);


CREATE TABLE Book(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(100) NOT NULL,
author varchar(100) NOT NULL,
year int not null,
person_id int REFERENCES Person(id));

INSERT INTO book(title, author, year)
values ('Над пропастью во ржи', 'Джером Сэлиджер', 1951);
INSERT INTO book(title, author, year)
values ('Я легенда', 'Ричард Мэтисон', 1954);
INSERT INTO book(title, author, year)
values ('Философия Java', 'Брюс Эскель', 2018);
INSERT INTO book(title, author, year)
values ('Сильмарион', 'Джон Рональд Руэл Толкин', 1977);
INSERT INTO book(title, author, year)
values ('Бойцовский клуб', 'Чак Паланник', 1996);
INSERT INTO book(title, author, year)
values ('Сто лет одиночества', 'Габриэль Гарсиа Маркес', 1967);